 import 'languages.dart';

const Map<String, dynamic> fa_string = {

  AppLocale.app_name: 'جاب یار',
  AppLocale.app_title: 'جاب یار - رزومه ساز آنلاین',
  AppLocale.home_subtitle:'قالب رزومه مورد نظر خود را از لیست زیر انتخاب نمایید برای مشاهده پیش نمایش  گزینه مورد نظر را نگهدارید',
  AppLocale.template_preview_title:'پیش نمایش قالب شماره',
  AppLocale.cv_builder:'رزومه ساز آنلاین',
  AppLocale.home_welcome:'خوش آمدید',

  AppLocale.download_cv:'دریافت رزومه',
  AppLocale.home_profile:'پروفایل',
  AppLocale.home_no_template_choosed:'هیچ قالبی انتخاب نکرده اید',
  AppLocale.home_cv_error:'خطایی رخ داده است',
  AppLocale.home_cv_downloaded:'رزومه شما با موفقیت دانلود شد',
  AppLocale.skill_dialog_content:'عملیات مورد نظر را برای این آیتم مشخص کنید',
  AppLocale.skill_subtitle:'لیست مهارت ها خود را در این بخش اضافه کنید',
  AppLocale.delete:'حذف',
  AppLocale.edit:'ویرایش',
  AppLocale.skill_hint:'برنامه نویسی',


  AppLocale.lang_subtitle:'مهارت های زبانی خود را در این قسمت میتوانید ثبت کنید ',
  AppLocale.language:'زبان ',
  AppLocale.language_hint:'انگلیسی ',
  AppLocale.lang_isempty:'لیست زبان شما خالی است ',
  AppLocale.success_submit:'اطلاعات شما ثبت شد ',
  AppLocale.error:'خطایی رخ داده است ',
  AppLocale.save:'ثبت ',
  AppLocale.fill_all : "تمام مقادیر را تکمیل کنید",
 AppLocale.desc : "توضیحات",
 AppLocale.desc_hint : "توضیحات موقعیت شغلی",
 AppLocale.date_start : "تاریخ شروع",
 AppLocale.date_end : "تاریخ پایان",
 AppLocale.job_title : "عنوان شغل",
 AppLocale.job_hint : "برنامه نویس",
 AppLocale.company_title : "نام شرکت",
 AppLocale.company_hint : "مایکروسافت",
 AppLocale.work_subtitle : "لیست سوابق کاری خود را در این قسمت ثبت کنید",
 AppLocale.work_title : "تجربه های کاری",
 AppLocale.work_empty : "سوابق کاری شما خالی است",
//
 AppLocale.ed_subtitle : "لیست تحصیلات و دوره های گذرانده شده در دانشگاه و موسسات",
 AppLocale.ed_pagetitle : "تحصیلات",
 AppLocale.ed_empty : "سوابق کاری شما خالی است",
 AppLocale.ed_title_hint : "مهندسی کامپیوتر",
 AppLocale.ed_title : "رشته تحصیلی",
 AppLocale.ed_grade : "مقطع",
 AppLocale.ed_grade_hint : "کارشناسی ارشد",
 AppLocale.ed_desc : "توضیحات(اختیاری)",
 AppLocale.ed_uni : "دانشگاه",
 AppLocale.ed_uni_hint : "صنعتی شریف",
 AppLocale.add : "اضافه کردن",

 AppLocale.social_title : "شبکه های اجتماعی",
 AppLocale.social_subtitle : "ثبت اطلاعات مرتبط با شبکه های اجتماعی",
 AppLocale.social_github : "گیتهاب",
 AppLocale.social_github_hint : "github.com",
 AppLocale.social_linkedin : "لینکدین",
 AppLocale.social_linkedin_hint : "linkedin.com",
 AppLocale.social_telegram : "تلگرام",
 AppLocale.social_telegram_hint : "Telegram.me",
 AppLocale.social_instagram : "اینستاگرام",
 AppLocale.social_instagram_hint : "Instagram.com",
 AppLocale.social_dribble : "دریبل",
 AppLocale.social_dribble_hint : "Dribble.com",
 AppLocale.social_site : "وبسایت",
 AppLocale.social_site_hint : "Site.com",


 AppLocale.personal_info : "اطلاعات شخصی",
 AppLocale.personal_info_subtitle : "ویرایش اطلاعات و مشخصات شخصی",
 AppLocale.email_hint : "آدرس ایمیل",
 AppLocale.email : "ایمیل",
 AppLocale.name_hint : "نام و نام خانوادگی",
 AppLocale.name : "نام",
 AppLocale.mobile_hint : "شماره تماس",
 AppLocale.mobile : "موبایل",
 AppLocale.bio_job_hint : "عنوان شغلی",
 AppLocale.bio_job : "شغل",
 AppLocale.birthday : "تاریخ تولد",
 AppLocale.birthday_date : "1402/1/1",
 AppLocale.location_hint : "محل زندگی",
 AppLocale.city : "شهر",
 AppLocale.bio_hint : "درباره خودتان توضیحاتی را بنویسید",
 AppLocale.bio : " بیوگرافی",
 AppLocale.choose_image : "تصویر پروفایل خود \n را انتخاب کنید",
  AppLocale.lang_setting_title : "زبان مورد نظر را انتخاب کنید",


};
