name: Build and Upload Signed APK

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify a compatible runner

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install Flutter
        uses: suborbital/flutter@v1  # Or any other preferred Flutter action
        with:
          flutter-version: '3.x'  # Update with your desired version

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}

        run: |
            echo $ENCODED_STRING > keystore-b64.txt
            base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH
      - name: Configure sig
        env:
          # Use encrypted secrets defined in GitHub Actions settings
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        # Decrypt and store credentials in temporary files
        run: |
          mkdir -p signing
          openssl enc -aes-256-cbc -k "${{ secrets.SIGNING_KEY_STORE_PATH }}" -d -in secrets/keystore.enc > signing/keystore.jks
          openssl enc -aes-256-cbc -k "${{ secrets.SIGNING_KEY_PASSWORD }}" -d -in secrets/key_password.enc > signing/key.password
          openssl enc -aes-256-cbc -k "${{ secrets.SIGNING_STORE_PASSWORD }}" -d -in secrets/store_password.enc > signing/store_password

      - name: Build signed APK (using Gradle)
        run: |
          ./gradlew assembleRelease \
            -Pandroid:signingConfigs=release \
            -PkeyStoreFile=signing/keystore.jks \
            -PkeyAlias=${{ secrets.SIGNING_KEY_ALIAS }} \
            -PstorePassword=file:signing/store_password \
            -PkeyPassword=file:signing/key.password

      - name: Upload signed APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: signed-apk
          path: /path/to/your/built/apk/file.apk  # Update with the actual path

