name: Build and Upload Signed Flutter App

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  tags:  # Trigger on tag pushes (optional)
    - v*  # Match tags starting with "v" (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest  # Specify a compatible runner

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install Flutter
        uses: suborbital/flutter@v1  # Or any other preferred Flutter action
        with:
          flutter-version: '3.x'  # Update with your desired version

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Configure signing credentials (**Secure way**)
        env:
          # Use encrypted secrets defined in GitHub Actions settings
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        # Decrypt and store credentials in temporary files (optional)
        run: |
          if [[ -n "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" ]]; then
            echo $ENCODED_STRING > keystore-b64.txt
            base64 -d keystore-b64.txt > signing/keystore.jks
          fi
          # Add logic for other encrypted secret formats (if applicable)

      - name: Build signed APK (using Gradle)
        run: |
          ./gradlew assembleRelease \
            -Pandroid:signingConfigs=release \
            -PkeyStoreFile=${{ secrets.SIGNING_KEY_STORE_PATH }}  # Use encrypted path if applicable
            -PkeyAlias=${{ secrets.SIGNING_KEY_ALIAS }} \
            -PstorePassword=file:signing/store_password (if using temporary file)
            -PkeyPassword=file:signing/key.password (if using temporary file)

      - name: Upload signed APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: signed-apk
          path: /path/to/your/built/apk/file.apk  # Update with the actual path

  # Optional job for app bundle (similar structure as build job)

